#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master

install:
  - git submodule update --init --recursive

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - powershell -file Build.ps1 -buildserver

after_build:
  - ps: cd _build/PreBuildWizard.AnyCPU.Release ; 7z.exe a PreBuildWizard-v$env:GitVersion_MajorMinorPatch.zip -x!*.pdb .
  
#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: '_build/PreBuildWizard.AnyCPU.Release\PreBuildWizard-v$(GitVersion_MajorMinorPatch).zip'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  tag: $(GitVersion_MajorMinorPatch)
  release: Product Release of v$(GitVersion_MajorMinorPatch)
  provider: GitHub
  auth_token:
    secure: HYngJp8YBsLRs4xGHt/P0ry3dVuu+FqEWvEJvVv4IOD6gFpxBAsQxz4yPjiy2dKp
  artifact: _build/PreBuildWizard.AnyCPU.Release\PreBuildWizard-v$(GitVersion_MajorMinorPatch).zip
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
